//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suma2Lealtad.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class CardsEntities : DbContext
    {
        public CardsEntities()
            : base("name=CardsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<PLZ_GETREPORT_Result> PLZ_GETREPORT(string fROMDATE, string uNTILDATE, string nUMDOC, string aCCOUNTTYPE, string tRX)
        {
            var fROMDATEParameter = fROMDATE != null ?
                new ObjectParameter("FROMDATE", fROMDATE) :
                new ObjectParameter("FROMDATE", typeof(string));
    
            var uNTILDATEParameter = uNTILDATE != null ?
                new ObjectParameter("UNTILDATE", uNTILDATE) :
                new ObjectParameter("UNTILDATE", typeof(string));
    
            var nUMDOCParameter = nUMDOC != null ?
                new ObjectParameter("NUMDOC", nUMDOC) :
                new ObjectParameter("NUMDOC", typeof(string));
    
            var aCCOUNTTYPEParameter = aCCOUNTTYPE != null ?
                new ObjectParameter("ACCOUNTTYPE", aCCOUNTTYPE) :
                new ObjectParameter("ACCOUNTTYPE", typeof(string));
    
            var tRXParameter = tRX != null ?
                new ObjectParameter("TRX", tRX) :
                new ObjectParameter("TRX", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PLZ_GETREPORT_Result>("PLZ_GETREPORT", fROMDATEParameter, uNTILDATEParameter, nUMDOCParameter, aCCOUNTTYPEParameter, tRXParameter);
        }
    }
}
